[programs.devnet]
token_cc = "4JXPnRBhruBCc2fxxGguCYpWwsHYNBrSQYxUPsjNPVAC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/heisenberg/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/claim.ts"
